### ISSUE TITLE
get_unique_cookies causes freeze

### ISSUE THREAD

**Issue by MaxAndolini** [omkarcloud/outlook-account-generator#10]
### Description

There is a problem I noticed when using it with a proxy. While trying to get the last cookie after the account opening process is completed, if the page continues to load, etc., in this case, it gets stuck in the driver.get(link) part of this function and the script does not continue unless you manually refresh the page.

![Unique](https://github.com/omkarcloud/outlook-account-generator/assets/6771759/89d20ce8-902a-450e-a6d2-204336d032e7)

Also, I asked you before, according to your system, I am trying to call a link to change the IP in every 3 accounts in the mobile proxy, but I could not solve the triggering in every 3 operations, even if I did the parallel operation thing to 1.

**Comment by Chetan11-dev** [comment]
Fixed, Please follow these Steps. 

⿡ Clone the Magic 🧙‍♀:
```
git clone https://github.com/omkarcloud/outlook-account-generator
cd outlook-account-generator
```

⿢ Install Dependencies 📦:
```
python -m pip install -r requirements.txt
```

⿣ Let's Roll 😎:
```
python main.py 
```

And Run the following command to update packages:

```
python -m pip install botasaurus --upgrade
```
