### ISSUE TITLE
Use a Fixed Password

### ISSUE THREAD

**Issue by shuskry** [omkarcloud/outlook-account-generator#10]
Hello,

I Would like to know if it's possible to use the same Passwords for all generated account ?

Thanks for your work ! 
Have a good day !

**Comment by Chetan11-dev** [comment]
Thank you for your suggestion. At this point of time, I'm not planning to add this feature. 

Most importantly because there hasn't been demand for it from the users.

However, if more users express interest in this feature in the future, I will certainly reconsider my decision.
Good Day!
