### ISSUE TITLE
Browser Issues

### ISSUE THREAD

**Issue by Rawi1005** [omkarcloud/outlook-account-generator#16]
hi having issue the browser does not started

version 120.0.6099.217 (Official Build) (64-bit)

having error about chromedriver does not added to the path
`   return self._return_or_raise()
  File "C:\Users\Windows\AppData\Local\Programs\Python\Python39\lib\site-packages\joblib\parallel.py", line 754, in _return_or_raise
    raise self._result
selenium.common.exceptions.WebDriverException: Message: 'chromedriver-120.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
`
![image](https://github.com/omkarcloud/outlook-account-generator/assets/101038560/242e9d76-d10d-4149-b597-396f09018329)

could you please look for me please thanks and appriciate your help

**Comment by Chetan11-dev** [comment]
@Rawi1005 I have released fixes, kindly use the latest version.

**Comment by Rawi1005** [comment]
Thanks
