### ISSUE TITLE
error when using autoslovecapchaapi

### ISSUE THREAD

**Issue by Rawi1005** [omkarcloud/outlook-account-generator#19]
### Description

Traceback (most recent call last):
  File "G:\outlook-account-generator\main.py", line 5, in <module>
    Outlook.create_accounts(key="CAP-5C8167B64E4FB2719623E0BD85AA6D54")
  File "G:\outlook-account-generator\src\outlook\outlook.py", line 76, in create_accounts
    ctd = create_accounts(ls, parallel = parallel)
TypeError: wrapper_browser() got an unexpected keyword argument 'parallel'

### Steps to Reproduce

1. put capslover api in the way the tutorial said  Outlook.create_accounts(key="CAP-example")
2. run
3. error

**Expected behavior:** run normally and slove capcha

**Actual behavior:** error

**Reproduces how often:** evertime but other funciton works fine

**Comment by Chetan11-dev** [comment]
Run
python -m pip install botasaurus --upgrade

**Comment by Rawi1005** [comment]
Thanks
