### ISSUE TITLE
Large Captchas Needed

### ISSUE THREAD

**Issue by Classickkk** [omkarcloud/outlook-account-generator#32]
every time it is attempted to create by the tool, it ends up asking for a huge captcha of 10.20 images, making it faster to create manually, possibly due to automation being detected by Microsoft, I believe it will be solved if you adapt this code to a library that interacts with the inputs of the system and not the browser, like Pyautogui

**Comment by Chetan11-dev** [comment]
Pyautogui can't be used because it doesn't support Dom Interactions.

**Comment by Classickkk** [comment]
Even though pyautogui is not compatible with DOM interactions, it does not mean that it is impossible to write code with the same objective that uses other forms of interaction, since several libraries could be mixed in the environment, given the complexity of your project, it is possible to achieve the same objective in other ways and with a relatively simpler structure, since unfortunately using a browser directly increases the antibot's risk rate too much, making your project unfeasible to be used, I particularly recommend using a macro library for interaction via OCR , and the other extra features of your project mixed into the environment using a database, direct requests, etc., using the machine's native browser instead of a WebDriver

**Comment by Chetan11-dev** [comment]
Any Code Examples?
