### ISSUE TITLE
Trying to implement 2Captcha support

### ISSUE THREAD

**Issue by Glama107** [omkarcloud/outlook-account-generator#35]
Hi !
I'm trying to implement a 2Captcha support for your generator, the code in solve_captcha.py looks like this :

`

      from twocaptcha import TwoCaptcha

          def solve_captcha(websitePublicKey, websiteURL, funcaptchaApiJSSubdomain, blob_data, useragent, proxy, capsolver_apikey):
          
                print("Captcha solving started...")
          
                config = {
                    'apiKey':           capsolver_apikey,
                }
          
                solver = TwoCaptcha(**config)
                
                try:
                        result = solver.funcaptcha(
          
                                sitekey=websitePublicKey,
                                url=websiteURL,
                                useragent=useragent,
                                data=blob_data,
                                funcaptchaApiJSSubdomain=funcaptchaApiJSSubdomain,
                        )
          
                except Exception as e:
                        return "DETECTED"
          
                else:
                        print('result',str(result))
                        return str(result['code'])
          

`

In my `main.py`I write this : `Outlook.create_accounts(key="TOKEN_2CAPTCHA_API")`
The captcha is correctly sent to 2Captcha and the response looks like this :

`result {'captchaId': '75323604525', 'code': '8e5e0445eca3ac357.e483a882d3|r=us-east-1|meta=3|meta_width=558|meta_height=523|metabgclr=transparent|metaiconclr=%23555555|guitextcolor=%23000000|lang=en|pk=B7D8911C-5CC8-A9A3-35B0-554ACEE604DA|at=40|ag=101|cdn_url=https%3A%2F%2Fclient-api.arkoselabs.com%2Fcdn%2Ffc|lurl=https%3A%2F%2Faudio-us-east-1.arkoselabs.com|surl=https%3A%2F%2Fclient-api.arkoselabs.com|smurl=https%3A%2F%2Fclient-api.arkoselabs.com%2Fcdn%2Ffc%2Fassets%2Fstyle-manager'}`

I return the 'code' part which is the token, but it's not solving the captcha and the navigator close after says 'Skipping Account Creation due to Detection.'

Do you know where I can work to solve this problem?

Thank's!

**Comment by diegoooooooooooooooo** [comment]
basically it's because the resolution of 2captcha is bad, there is a second captcha which arrives which gives a detection and closes the browser

**Comment by Chetan11-dev** [comment]
Yes, it has been detected that there is an issue with the current Captcha Solvers, which are failing to save this Captcha. Due to some reasons, they are not functioning as expected. Please wait until January 3rd, by which time I will attempt to implement an alternative captcha solver, such as 2Captcha or AnyCaptcha.
