### ISSUE TITLE
Cannot find the build/ folder directory

### ISSUE THREAD

**Issue by Sdc-glitch** [omkarcloud/outlook-account-generator#5]
"Place the "chromedriver" file (or "chromedriver.exe" if you are using Windows) directly into the build/ folder. Make sure you're not placing the extracted folder but only the chrome driver file itself."

I was not able to locate the build/ folder directory, Please provide a path or something to help locate the folder to put the chromedriver.

Platform used: Windows x64

**Comment by Chetan11-dev** [comment]
Create build folder if not exisits in the folder.

**Comment by Chetan11-dev** [comment]
This has been
