### ISSUE TITLE
the creating is so slow

### ISSUE THREAD

**Issue by XaiMTM** [omkarcloud/outlook-account-generator#9]
Sleeping for 7.101102159976938 seconds...
Sleeping for 2.799410218653983 seconds...
Sleeping for 6.178260119815528 seconds...
Sleeping for 2.641663142995085 seconds...
Sleeping for 3.2470248799191204 seconds...
Sleeping for 3.317110192852514 seconds...
Sleeping for 3.105927510994545 seconds...
Sleeping for 3.0500390137506144 seconds...
Sleeping for 3.8526183634563864 seconds...
Sleeping for 3.3242916677904404 seconds...
Sleeping for 2.107843100754644 seconds...

**Comment by Chetan11-dev** [comment]
I deliberately made it slow and random to mimic humans avoid getting detected.

**Comment by Chetan11-dev** [comment]
Made it fast, Please follow these Steps. 

1️⃣ **Clone the Magic 🧙‍♀:**
   ```shell
   git clone https://github.com/omkarcloud/outlook-account-generator
   cd outlook-account-generator
   ```
2️⃣ **Install Dependencies 📦:**
   ```shell
   python -m pip install -r requirements.txt
   ```
3️⃣ **Let the Rain of Outlook Accounts Begin 😎:**
   ```shell
   python main.py
   ```
   
And Run the following command to update packages:

```
python -m pip install botasaurus --upgrade
```
